// ポケモンスリープ 食材・料理データ
// 食材リスト（表示順）
const INGREDIENTS = [
  { id: "mamemeat", name: "マメミート" },
  { id: "gekikara", name: "げきからハーブ" },
  { id: "atataka", name: "あったかジンジャー" },
  { id: "ajiwai", name: "あじわいキノコ" },
  { id: "moomoo", name: "モーモーミルク" },
  { id: "hokkori", name: "ほっこりポテト" },
  { id: "pure_oil", name: "ピュアなオイル" },
  { id: "tsuyatsuya", name: "つやつやアボカド" },
  { id: "futoi_negi", name: "ふといながねぎ" },
  { id: "tokusen_egg", name: "とくせんエッグ" },
  { id: "amai_mitsu", name: "あまいミツ" },
  { id: "wakakusa_daizu", name: "ワカクサ大豆" },
  { id: "anmin_tomato", name: "あんみんトマト" },
  { id: "mezamashi_coffee", name: "めざましコーヒー" },
  { id: "zusshiri_kabocha", name: "ずっしりカボチャ" },
  { id: "wakakusa_corn", name: "ワカクサコーン" },
  { id: "relax_cacao", name: "リラックスカカオ" },
  { id: "tokusen_apple", name: "とくせんリンゴ" },
  { id: "oishii_shippo", name: "おいしいシッポ" },
];

// 料理データ（カテゴリ / 料理名 / 必要食材と数量 / 基本エナジー値 / 食材の数ボーナス倍率）
// 食材名は INGREDIENTS の name と一致させる
const RECIPES = [
  // ==== カレー・シチュー ====
  { category: "カレー・シチュー", name: "とびはねるカレーうどん", energy: 25539, multiplier: 1.78, ingredients: { "マメミート": 20, "げきからハーブ": 22, "あったかジンジャー": 39, "あじわいキノコ": 31 } },
  { category: "カレー・シチュー", name: "しんりょくアボカドグラタン", energy: 24802, multiplier: 1.78, ingredients: { "モーモーミルク": 41, "ほっこりポテト": 20, "ピュアなオイル": 32, "つやつやアボカド": 22 } },
  { category: "カレー・シチュー", name: "いあいぎりすき焼きカレー", energy: 20655, multiplier: 1.61, ingredients: { "マメミート": 26, "ふといながねぎ": 27, "とくせんエッグ": 22, "あまいミツ": 26 } },
  { category: "カレー・シチュー", name: "めざめるパワーシチュー", energy: 19061, multiplier: 1.61, ingredients: { "ワカクサ大豆": 28, "あんみんトマト": 25, "あじわいキノコ": 23, "めざましコーヒー": 16 } },
  { category: "カレー・シチュー", name: "なりきりバケッチャシチュー", energy: 15621, multiplier: 1.48, ingredients: { "マメミート": 16, "ほっこりポテト": 18, "あじわいキノコ": 25, "ずっしりカボチャ": 10 } },
  { category: "カレー・シチュー", name: "れんごくコーンキーマカレー", energy: 13690, multiplier: 1.48, ingredients: { "マメミート": 24, "げきからハーブ": 27, "あったかジンジャー": 12, "ワカクサコーン": 14 } },
  { category: "カレー・シチュー", name: "ワカクサカレーパン", energy: 10945, multiplier: 1.48, ingredients: { "ワカクサ大豆": 8, "ピュアなオイル": 15, "げきからハーブ": 20, "あったかジンジャー": 20 } },
  { category: "カレー・シチュー", name: "ニンジャカレー", energy: 9445, multiplier: 1.48, ingredients: { "ワカクサ大豆": 24, "マメミート": 9, "ふといながねぎ": 12, "あじわいキノコ": 5 } },
  { category: "カレー・シチュー", name: "ぜったいねむりバターカレー", energy: 9010, multiplier: 1.35, ingredients: { "リラックスカカオ": 12, "モーモーミルク": 10, "ほっこりポテト": 18, "あんみんトマト": 15 } },
  { category: "カレー・シチュー", name: "あぶりテールカレー", energy: 7483, multiplier: 1.25, ingredients: { "げきからハーブ": 25, "おいしいシッポ": 8 } },
  { category: "カレー・シチュー", name: "からくちネギもりカレー", energy: 5900, multiplier: 1.25, ingredients: { "ふといながねぎ": 14, "げきからハーブ": 8, "あったかジンジャー": 10 } },
  { category: "カレー・シチュー", name: "ピヨピヨパンチ辛口カレー", energy: 5702, multiplier: 1.35, ingredients: { "げきからハーブ": 11, "あまいミツ": 11, "めざましコーヒー": 11 } },
  { category: "カレー・シチュー", name: "じゅうなんコーンシチュー", energy: 4670, multiplier: 1.25, ingredients: { "モーモーミルク": 8, "ほっこりポテト": 8, "ワカクサコーン": 14 } },
  { category: "カレー・シチュー", name: "おやこあいカレー", energy: 4523, multiplier: 1.25, ingredients: { "ほっこりポテト": 4, "とくせんリンゴ": 11, "とくせんエッグ": 8, "あまいミツ": 12 } },
  { category: "カレー・シチュー", name: "キノコのほうしカレー", energy: 4162, multiplier: 1.17, ingredients: { "ほっこりポテト": 9, "あじわいキノコ": 14 } },
  { category: "カレー・シチュー", name: "ビルドアップマメカレー", energy: 3372, multiplier: 1.17, ingredients: { "ワカクサ大豆": 12, "マメミート": 6, "とくせんエッグ": 4, "げきからハーブ": 4 } },
  { category: "カレー・シチュー", name: "ほっこりホワイトシチュー", energy: 3181, multiplier: 1.17, ingredients: { "モーモーミルク": 10, "ほっこりポテト": 8, "あじわいキノコ": 4 } },
  { category: "カレー・シチュー", name: "とけるオムカレー", energy: 2150, multiplier: 1.11, ingredients: { "とくせんエッグ": 10, "あんみんトマト": 6 } },
  { category: "カレー・シチュー", name: "サンパワートマトカレー", energy: 2078, multiplier: 1.11, ingredients: { "げきからハーブ": 5, "あんみんトマト": 10 } },
  { category: "カレー・シチュー", name: "ひでりカツレツカレー", energy: 1942, multiplier: 1.11, ingredients: { "マメミート": 10, "ピュアなオイル": 5 } },
  { category: "カレー・シチュー", name: "満腹チーズバーグカレー", energy: 1910, multiplier: 1.11, ingredients: { "モーモーミルク": 8, "マメミート": 8 } },
  { category: "カレー・シチュー", name: "マメバーグカレー", energy: 856, multiplier: 1.06, ingredients: { "マメミート": 7 } },
  { category: "カレー・シチュー", name: "ベイビィハニーカレー", energy: 839, multiplier: 1.06, ingredients: { "あまいミツ": 7 } },
  { category: "カレー・シチュー", name: "たんじゅんホワイトシチュー", energy: 814, multiplier: 1.06, ingredients: { "モーモーミルク": 7 } },
  { category: "カレー・シチュー", name: "とくせんリンゴカレー", energy: 748, multiplier: 1.06, ingredients: { "とくせんリンゴ": 7 } },

  // ==== サラダ ====
  { category: "サラダ", name: "ごろごろねっとうサラダ", energy: 25356, multiplier: 1.61, ingredients: { "ほっこりポテト": 30, "あじわいキノコ": 27, "ワカクサコーン": 18, "ずっしりカボチャ": 20 } },
  { category: "サラダ", name: "じならしワカモレチップス", energy: 25162, multiplier: 1.78, ingredients: { "ワカクサ大豆": 22, "げきからハーブ": 30, "ワカクサコーン": 25, "つやつやアボカド": 28 } },
  { category: "サラダ", name: "まけんきコーヒーサラダ", energy: 20218, multiplier: 1.61, ingredients: { "マメミート": 28, "ほっこりポテト": 22, "ピュアなオイル": 22, "めざましコーヒー": 28 } },
  { category: "サラダ", name: "りんごさんヨーグルトサラダ", energy: 19293, multiplier: 1.78, ingredients: { "モーモーミルク": 18, "とくせんリンゴ": 28, "とくせんエッグ": 35, "あんみんトマト": 23 } },
  { category: "サラダ", name: "はなふぶきミモザサラダ", energy: 11811, multiplier: 1.47, ingredients: { "マメミート": 12, "ほっこりポテト": 15, "ピュアなオイル": 17, "とくせんエッグ": 25 } },
  { category: "サラダ", name: "ニンジャサラダ", energy: 11659, multiplier: 1.48, ingredients: { "ワカクサ大豆": 19, "ふといながねぎ": 15, "あったかジンジャー": 11, "あじわいキノコ": 12 } },
  { category: "サラダ", name: "ワカクササラダ", energy: 11393, multiplier: 1.48, ingredients: { "ほっこりポテト": 9, "ピュアなオイル": 22, "あんみんトマト": 14, "ワカクサコーン": 17 } },
  { category: "サラダ", name: "クロスチョップドサラダ", energy: 8755, multiplier: 1.35, ingredients: { "マメミート": 15, "とくせんエッグ": 20, "あんみんトマト": 10, "ワカクサコーン": 11 } },
  { category: "サラダ", name: "ヤドンテールのペッパーサラダ", energy: 8169, multiplier: 1.25, ingredients: { "ピュアなオイル": 15, "げきからハーブ": 10, "おいしいシッポ": 10 } },
  { category: "サラダ", name: "めいそうスイートサラダ", energy: 7675, multiplier: 1.48, ingredients: { "とくせんリンゴ": 21, "あまいミツ": 16, "ワカクサコーン": 12 } },
  { category: "サラダ", name: "くだけるアボカドサラダ", energy: 7125, multiplier: 1.35, ingredients: { "ワカクサ大豆": 18, "ピュアなオイル": 10, "つやつやアボカド": 14 } },
  { category: "サラダ", name: "キノコのほうしサラダ", energy: 5859, multiplier: 1.25, ingredients: { "ピュアなオイル": 8, "あんみんトマト": 8, "あじわいキノコ": 17 } },
  { category: "サラダ", name: "オーバーヒートサラダ", energy: 5225, multiplier: 1.25, ingredients: { "げきからハーブ": 17, "あんみんトマト": 8, "あったかジンジャー": 10 } },
  { category: "サラダ", name: "くいしんぼうポテトサラダ", energy: 5040, multiplier: 1.25, ingredients: { "マメミート": 7, "ほっこりポテト": 14, "とくせんリンゴ": 6, "とくせんエッグ": 9 } },
  { category: "サラダ", name: "ムラっけチョコミートサラダ", energy: 3665, multiplier: 1.17, ingredients: { "リラックスカカオ": 14, "マメミート": 9 } },
  { category: "サラダ", name: "うるおいとうふサラダ", energy: 3113, multiplier: 1.25, ingredients: { "ワカクサ大豆": 15, "あんみんトマト": 9 } },
  { category: "サラダ", name: "ばかぢからワイルドサラダ", energy: 3046, multiplier: 1.17, ingredients: { "マメミート": 9, "ほっこりポテト": 3, "とくせんエッグ": 5, "あったかジンジャー": 6 } },
  { category: "サラダ", name: "モーモーカプレーゼ", energy: 2942, multiplier: 1.17, ingredients: { "モーモーミルク": 12, "ピュアなオイル": 5, "あんみんトマト": 6 } },
  { category: "サラダ", name: "めんえきねぎサラダ", energy: 2845, multiplier: 1.11, ingredients: { "ふといながねぎ": 10, "あったかジンジャー": 5 } },
  { category: "サラダ", name: "みだれづきコーンサラダ", energy: 2785, multiplier: 1.25, ingredients: { "ピュアなオイル": 8, "ワカクサコーン": 9 } },
  { category: "サラダ", name: "メロメロりんごのチーズサラダ", energy: 2655, multiplier: 1.17, ingredients: { "モーモーミルク": 5, "ピュアなオイル": 3, "とくせんリンゴ": 15 } },
  { category: "サラダ", name: "ねっぷうとうふサラダ", energy: 2114, multiplier: 1.11, ingredients: { "ワカクサ大豆": 10, "げきからハーブ": 6 } },
  { category: "サラダ", name: "ゆきかきシーザーサラダ", energy: 1898, multiplier: 1.11, ingredients: { "モーモーミルク": 10, "マメミート": 6 } },
  { category: "サラダ", name: "あんみんトマトサラダ", energy: 1045, multiplier: 1.06, ingredients: { "あんみんトマト": 8 } },
  { category: "サラダ", name: "マメハムサラダ", energy: 978, multiplier: 1.06, ingredients: { "マメミート": 8 } },
  { category: "サラダ", name: "とくせんリンゴサラダ", energy: 855, multiplier: 1.06, ingredients: { "とくせんリンゴ": 8 } },

  // ==== デザート・ドリンク ====
  { category: "デザート・ドリンク", name: "みつあつめチョコワッフル", energy: 25484, multiplier: 1.78, ingredients: { "リラックスカカオ": 21, "ピュアなオイル": 28, "あまいミツ": 38, "ワカクサコーン": 28 } },
  { category: "デザート・ドリンク", name: "ドキドキこわいかおパンケーキ", energy: 24354, multiplier: 1.78, ingredients: { "とくせんエッグ": 24, "あんみんトマト": 29, "あまいミツ": 32, "ずっしりカボチャ": 18 } },
  { category: "デザート・ドリンク", name: "ドオーのエクレア", energy: 20885, multiplier: 1.61, ingredients: { "リラックスカカオ": 30, "モーモーミルク": 26, "あまいミツ": 22, "めざましコーヒー": 24 } },
  { category: "デザート・ドリンク", name: "スパークスパイスコーラ", energy: 17494, multiplier: 1.61, ingredients: { "ふといながねぎ": 20, "とくせんリンゴ": 35, "あったかジンジャー": 20, "めざましコーヒー": 12 } },
  { category: "デザート・ドリンク", name: "フラワーギフトマカロン", energy: 13834, multiplier: 1.48, ingredients: { "リラックスカカオ": 25, "モーモーミルク": 10, "とくせんエッグ": 25, "あまいミツ": 17 } },
  { category: "デザート・ドリンク", name: "おちゃかいコーンスコーン", energy: 10925, multiplier: 1.48, ingredients: { "モーモーミルク": 9, "とくせんリンゴ": 20, "あったかジンジャー": 20, "ワカクサコーン": 18 } },
  { category: "デザート・ドリンク", name: "グラスミキサースムージー", energy: 8165, multiplier: 1.35, ingredients: { "モーモーミルク": 14, "あんみんトマト": 16, "つやつやアボカド": 18 } },
  { category: "デザート・ドリンク", name: "プリンのプリンアラモード", energy: 7594, multiplier: 1.35, ingredients: { "モーモーミルク": 10, "とくせんリンゴ": 10, "とくせんエッグ": 15, "あまいミツ": 20 } },
  { category: "デザート・ドリンク", name: "かたやぶりコーンティラミス", energy: 7125, multiplier: 1.35, ingredients: { "モーモーミルク": 12, "ワカクサコーン": 14, "めざましコーヒー": 14 } },
  { category: "デザート・ドリンク", name: "はやおきコーヒーゼリー", energy: 6793, multiplier: 1.35, ingredients: { "モーモーミルク": 14, "あまいミツ": 12, "めざましコーヒー": 16 } },
  { category: "デザート・ドリンク", name: "だいばくはつポップコーン", energy: 6048, multiplier: 1.35, ingredients: { "モーモーミルク": 7, "ピュアなオイル": 14, "ワカクサコーン": 15 } },
  { category: "デザート・ドリンク", name: "ちからもちソイドーナッツ", energy: 5547, multiplier: 1.35, ingredients: { "ワカクサ大豆": 16, "リラックスカカオ": 7, "ピュアなオイル": 12 } },
  { category: "デザート・ドリンク", name: "ネロリのデトックスティー", energy: 5065, multiplier: 1.25, ingredients: { "とくせんリンゴ": 15, "あったかジンジャー": 11, "あじわいキノコ": 9 } },
  { category: "デザート・ドリンク", name: "ふくつのジンジャークッキー", energy: 4921, multiplier: 1.25, ingredients: { "リラックスカカオ": 5, "とくせんエッグ": 4, "あまいミツ": 14, "あったかジンジャー": 12 } },
  { category: "デザート・ドリンク", name: "あくまのキッスフルーツオレ", energy: 4734, multiplier: 1.25, ingredients: { "リラックスカカオ": 8, "モーモーミルク": 9, "とくせんリンゴ": 11, "あまいミツ": 7 } },
  { category: "デザート・ドリンク", name: "あまいかおりチョコケーキ", energy: 3378, multiplier: 1.17, ingredients: { "リラックスカカオ": 8, "モーモーミルク": 7, "あまいミツ": 9 } },
  { category: "デザート・ドリンク", name: "はなびらのまいチョコタルト", energy: 3314, multiplier: 1.25, ingredients: { "リラックスカカオ": 11, "とくせんリンゴ": 11 } },
  { category: "デザート・ドリンク", name: "はりきりプロテインスムージー", energy: 3168, multiplier: 1.17, ingredients: { "ワカクサ大豆": 15, "リラックスカカオ": 8 } },
  { category: "デザート・ドリンク", name: "おおきいマラサダ", energy: 3015, multiplier: 1.17, ingredients: { "モーモーミルク": 7, "ピュアなオイル": 10, "あまいミツ": 6 } },
  { category: "デザート・ドリンク", name: "マイペースやさいジュース", energy: 1924, multiplier: 1.11, ingredients: { "とくせんリンゴ": 7, "あんみんトマト": 9 } },
  { category: "デザート・ドリンク", name: "かるわざソイケーキ", energy: 1924, multiplier: 1.11, ingredients: { "ワカクサ大豆": 7, "とくせんエッグ": 8 } },
  { category: "デザート・ドリンク", name: "ひのこのジンジャーティー", energy: 1913, multiplier: 1.11, ingredients: { "とくせんリンゴ": 7, "あったかジンジャー": 9 } },
  { category: "デザート・ドリンク", name: "じゅくせいスイートポテト", energy: 1907, multiplier: 1.11, ingredients: { "モーモーミルク": 5, "ほっこりポテト": 9 } },
  { category: "デザート・ドリンク", name: "ねがいごとアップルパイ", energy: 1748, multiplier: 1.11, ingredients: { "モーモーミルク": 4, "とくせんリンゴ": 12 } },
  { category: "デザート・ドリンク", name: "クラフトサイコソーダ", energy: 1079, multiplier: 1.06, ingredients: { "あまいミツ": 9 } },
  { category: "デザート・ドリンク", name: "とくせんリンゴジュース", energy: 855, multiplier: 1.06, ingredients: { "とくせんリンゴ": 8 } },
  { category: "デザート・ドリンク", name: "モーモーホットミルク", energy: 814, multiplier: 1.06, ingredients: { "モーモーミルク": 7 } },
];
